services:
  server:
    depends_on:
      - redis
    build: .
    ports:
      - "8000:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_PORT=8080
      - JWT_SECRET=secret

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"